## Introduction to Numpy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.  
### Which Language is NumPy written in?
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.



## Why Use NumPy?
- In Python we have lists that serve the purpose of arrays, but they are slow to process.  
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
### Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.This behavior is called locality of reference in computer science.
This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.ures.

### Installing Numpy
Write `pip install numpy` in your command line.

#### Importing NumPy

In [8]:
import numpy as np

### What is array?
In computer programming, an array is a structure for storing and retrieving data. We often talk about an array as if it were a grid in space, with each cell storing one element of the data.  

## Numpy Array

A **NumPy array** is a numerically ordered sequence of elements stored contiguously in memory, that can store elements of homogeneous types (usually numbers but can be boolians, strings, or other objects), is iterable, mutable, non-growable/shrinkable and allows duplicate elements.

#### Example:

In [15]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

#### 2d-Array

In [18]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### N-dimensional Array

The fundamental array class is called ndarray: it represents an “N-dimensional array”.

Most NumPy arrays have some restrictions. For instance:
- All elements of the array must be of the same type of data.
- Once created, the total size of the the array can’t change.
- The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

When these conditions are met, NumPy exploits these characteristics to make the array faster, more memory efficient, and more convenient to use than less restrictive data structures.

## Array Attributes
- `ndim` It tells the number of dimensions of array.
- `shape` The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.
- `size` The fixed, total number of elements in array.
- `dtype` It tells the data type of elements of array.
- `nbytes` Total bytes consumed by the elements of the array.
- `itemsize` Length of one array element in bytes.



In [47]:
arr = np.array([[1,2,3],
               [4,5,6]])
print("The dimensions of Array: ",arr.ndim)
print("The shape of Array: ",arr.shape)
print("The size of Array: ",arr.size)
print("The datatype of Array: ",arr.dtype)
print("Total bytes consumed by Array: ",arr.nbytes)
print("Memory in bytes occupied by each element of Array: ",arr.itemsize)
print("Array: ",arr)

The dimensions of Array:  2
The shape of Array:  (2, 3)
The size of Array:  6
The datatype of Array:  int32
Total bytes consumed by Array:  24
Memory in bytes occupied by each element of Array:  4
Array:  [[1 2 3]
 [4 5 6]]


## Creating Numpy Arrays with built-in functions:
- `np.zeros()`
- `np.ones()`
- `np.empty()`
- `np.arange`
- `np.linspace`

### 1. np.zeros()  
This method returns an array of given shape and type, filled with zeros.
- np.zeros(shape, dtype=float)


In [72]:
arr = np.zeros((1,5),dtype=int)
arr

array([[0, 0, 0, 0, 0]])

### 2. np.ones()
This method returns an array of given shape and type, filled with ones.
- np.ones(shape, dtype=float)

In [76]:
arr = np.ones((1,5),dtype=int)
arr

array([[1, 1, 1, 1, 1]])

### 3. np.empty()

The function **np.empty()** creates an array whose initial content is random and depends on the state of the memory. 
- np.empty(shape, dtype=float)

In [95]:
arr = np.empty((2,5),dtype=int)
arr

array([[-1223002760,       32766,           0,         584,         792],
       [          0,         768,       32766,           0,           0]])

### 4. np.arange()
This function is used to get evenly spaced values within a given interval.
- np.arange(start=,stop=)

In [115]:
arr = np.arange(start=1,stop=10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### np.linspace()
You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval.
- np.linspace(start=,stop=,num=)

In [134]:
arr = np.linspace(start=1,stop=20,num=10)
arr

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

### Sorting an array

In [141]:
arr = np.array([2,9,6,4,2,5,1,10])
np.sort(arr)

array([ 1,  2,  2,  4,  5,  6,  9, 10])

### Concatenating Arrays

It joins two or more arrays in a single array.

In [144]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [146]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [148]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

### Reshaping Array
Using `arr.reshape()` will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [156]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [158]:
arr.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### Indexing and slicing
You can index and slice NumPy arrays in the same ways you can slice Python lists.

In [163]:
arr = np.array([1, 2, 3])
arr[1]

2

In [165]:
arr[0:2]

array([1, 2])

In [167]:
arr[1:]

array([2, 3])

In [173]:
arr[-1:]

array([3])

In [175]:
arr[-2:]

array([2, 3])

You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you’ll need to subset, slice, and/or index your arrays.

If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.



In [179]:
arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

You can easily print all of the values in the array that are less than 5.

In [182]:
print(arr[arr < 5])

[1 2 3 4]


You can select elements that are divisible by 2:

In [186]:
divisible_by_2 = arr[arr%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


## Creating an Array from existing Data:
- `slicing and indexing`
- `np.vstack()`
- `np.hstack()`
- `np.hsplit()`
- `view()`
- `copy()`

You can easily create a new array from a section of an existing array.

In [194]:
arr = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

You can create a new array from a section of your array any time by specifying where you want to slice your array.

In [197]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

You can also stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, `arr1` and `arr2`:

In [201]:
arr1 = np.array([[1, 1],
               [2, 2]])
arr2 = np.array([[3, 3],
               [4, 4]])

You can stack them vertically with `vstack`:

In [204]:
np.vstack((arr1, arr2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

You can stack them horizontally with `hstack`:

In [209]:
np.hstack((arr1, arr2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

You can split an array into several smaller arrays using `hsplit`. You can specify either the number of equally shaped arrays to return or the columns after which the division should occur.

In [224]:
arr = np.array([[1,2,3,4,5,2],
                [4,6,7,8,9,3]])

In [226]:
np.hsplit(arr,2)

[array([[1, 2, 3],
        [4, 6, 7]]),
 array([[4, 5, 2],
        [8, 9, 3]])]

If you wanted to split your array after the 2nd and 4th column, you’d run:

In [233]:
np.hsplit(arr,(2,4))

[array([[1, 2],
        [4, 6]]),
 array([[3, 4],
        [7, 8]]),
 array([[5, 2],
        [9, 3]])]

You can use the `view` method to create a new array object that looks at the same data as the original array (a shallow copy).

Views are an important NumPy concept! NumPy functions, as well as operations like indexing and slicing, will return views whenever possible. This saves memory and is faster (no copy of the data has to be made). However it’s important to be aware of this - modifying data in a view also modifies the original array!

In [249]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

Now we create an array `arr1` by slicing `arr` and modify the first element of `arr1`. This will modify the corresponding element in `arr` as well.

In [253]:
arr1 = arr[0:]
arr1

array([0, 1, 2, 3, 4])

In [255]:
arr1[0] = 9

In [259]:
arr,arr1

(array([9, 1, 2, 3, 4]), array([9, 1, 2, 3, 4]))

Using the `copy` method will make a complete copy of the array and its data (a deep copy). To use this on your array, you could run:

In [262]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

Now we create an array `arr1` by slicing `arr` and modify the first element of `arr1`. This will not modify the corresponding element in `arr`.

In [266]:
arr1 = arr.copy()
arr1

array([0, 1, 2, 3, 4])

In [268]:
arr1[0] = 9

In [270]:
arr,arr1

(array([0, 1, 2, 3, 4]), array([9, 1, 2, 3, 4]))

## Basic Operations
- `addition`
- `subtraction`
- `multiplication`
- `division`

In [282]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [284]:
arr1+arr2

array([5, 7, 9])

In [286]:
arr1-arr2

array([-3, -3, -3])

In [288]:
arr1*arr2

array([ 4, 10, 18])

In [290]:
arr2/arr1

array([4. , 2.5, 2. ])

If you want to find the sum of the elements in an array, you’d use `sum()`. This works for 1D arrays, 2D arrays, and arrays in higher dimensions.

In [295]:
arr = np.array([1, 2, 3, 4])
arr.sum()

10

In [297]:
b = np.array([[1, 1], [2, 2]])

You can sum over the axis of rows with:

In [300]:
b.sum(axis=0)

array([3, 3])

You can sum over the axis of columns with:

In [303]:
b.sum(axis=1)

array([2, 4])

## Broadcasting
There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes.

In [307]:
arr = np.array([1, 2])
arr*3

array([3, 6])

## Basic Statistics Functions
- maximum
- minimum
- sum
- mean
- product
- standard deviation

In [313]:
arr = np.array([1,2,3,4,5])

In [315]:
arr.max()

5

In [317]:
arr.min()

1

In [319]:
arr.sum()

15

In [321]:
arr.mean()

3.0

In [325]:
arr.prod()

120

In [327]:
arr.std()

1.4142135623730951

### Unique Elements of Array
You can find the unique elements in an array easily with `np.unique`.

In [332]:
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [334]:
np.unique(arr)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

To get the indices of unique values in a NumPy array, just pass the `return_index` argument in `np.unique()` as well as your array.

In [337]:
np.unique(arr,return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64))

You can pass the `return_counts` argument in `np.unique()` along with your array to get the frequency count of unique values in a NumPy array.

In [340]:
np.unique(arr,return_counts=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1], dtype=int64))

### Transpose of Matrix
You can take transpose(interchange rows and columns) of a matrix with `arr.transpose()` and `arr.T`

In [344]:
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])

In [346]:
arr.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [348]:
arr.T

array([[1, 3, 5],
       [2, 4, 6]])

### Reversing an Array
NumPy’s `np.flip()` function allows you to flip, or reverse, the contents of an array along an axis.

In [352]:
arr = np.array([1,2,3,4,5])

In [354]:
np.flip(arr)

array([5, 4, 3, 2, 1])

#### Reversing 2d-Array

In [357]:
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])

You can reverse the content in all of the rows and all of the columns with:

In [359]:
np.flip(arr)

array([[6, 5],
       [4, 3],
       [2, 1]])

You can easily reverse only the rows with:

In [363]:
np.flip(arr,axis=0)

array([[5, 6],
       [3, 4],
       [1, 2]])

You can easily reverse only the columns with:

In [367]:
np.flip(arr,axis=1)

array([[2, 1],
       [4, 3],
       [6, 5]])

You can also reverse the contents of only one column or row. For example, you can reverse the contents of the row at index position 2.

In [372]:
np.flip(arr[2])

array([6, 5])

### Flattening multidimensional arrays
- flatten()
- ravel()

In [376]:
arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

You can use `flatten` to flatten your array into a 1D array. When you use `flatten`, changes to your new array won’t change the parent array.

In [380]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

But when you use `ravel`, the changes you make to the new array will affect the parent array.

In [383]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Array with Random values
Numpy allows you to use various functions to produce arrays with random values. To access these functions, first we have to access the random function itself. This is done using `np.random`, after which we specify which function we need. Here is a list of the most used random functions and their purpose:
- `np.random.rand()`
- `np.random.randn()`
- `np.random.randint()`

**np.random.rand()** produce random values in the given shape from 0 to 1

In [391]:
np.random.rand()

0.79133167931571

In [393]:
np.random.rand(3)

array([0.86793788, 0.46871584, 0.99279709])

In [395]:
np.random.rand(2,2)

array([[0.94933783, 0.803309  ],
       [0.72436004, 0.67120132]])

**np.random.randn()** produce random values with a ‘standard normal’ distribution, from -1 to 1

In [418]:
np.random.randn()

1.2976753352290595

In [399]:
np.random.randn(3)

array([-0.1380559 , -0.13666659,  1.12617832])

In [401]:
np.random.randn(2,2)

array([[-0.31048728, -1.14890978],
       [ 1.36022365, -0.7074852 ]])

**np.random.randint()** produce random numbers from low to high, specified as parameter

In [411]:
np.random.randint(low=1, high=100)

30

In [409]:
np.random.randint(low=1, high=100, size=20)

array([81, 49, 18, 13, 31, 81, 21, 55,  3, 70, 38, 43, 70, 87, 44, 36, 50,
       94, 27, 96])

In [405]:
np.random.randint(low=1, high=100, size=(5,3))

array([[37, 59, 21],
       [67, 37, 21],
       [85,  8, 15],
       [65, 16,  6],
       [42, 30, 27]])

### Help()
Python has a built-in `help()` function that can help you access the information about concise summary of the object and how to use it.  This means that nearly any time you need more information, you can use `help()` to quickly find the information that you need.

In [427]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



You can also use `?`.

In [429]:
sum?

Signature: sum(iterable, /, start=0)
Docstring:
Return the sum of a 'start' value (default: 0) plus an iterable of numbers

When the iterable is empty, return the start value.
This function is intended specifically for use with numeric values and may
reject non-numeric types.
Type:      builtin_function_or_method